# Dockerfile to create image for infinidat k8s provisioner
FROM registry.access.redhat.com/rhel7

LABEL name="APPLICATION NAME" \
      maintainer="EMAIL@ADDRESS.COM" \
      vendor="COMPANY NAME" \
      version="VERSION NUMBER" \
      release="RELEASE NUMBER" \
      summary="APPLICATION SUMMARY" \
      description="APPLICATION DESCRIPTION"

COPY licenses /licenses

RUN yum -y update-minimal --disablerepo "*" --enablerepo rhel-7-server-rpms --setopt=tsflags=nodocs \
      --security --sec-severity=Important --sec-severity=Critical && \
    yum clean all

RUN mkdir -p /export

COPY deploy/docker/infinidat-k8s-provisioner ./infinidat-k8s-provisioner

#Adding user to avoid running of container in root mode
RUN useradd -m  infinidat

USER infinidat

ENTRYPOINT ["./infinidat-k8s-provisioner"]

