# Dockerfile to create image for infinidat k8s provisioner
FROM registry.access.redhat.com/rhel7

LABEL maintainer="connect-tech@redhat.com"

COPY licenses /licenses

RUN mkdir -p /export

COPY deploy/docker/infinidat-k8s-provisioner ./infinidat-k8s-provisioner

#Adding user to avoid running of container in root mode
RUN useradd -m  infinidat

USER infinidat

ENTRYPOINT ["./infinidat-k8s-provisioner"]

